added sysbrowse

diff --git a/sysno b/sysno
--- a/sysno
+++ b/sysno
@@ -10,7 +10,7 @@ get_def() {
 	while read -r line; do
 		case "$line" in
 			"#define __NR_$1 "*)
-				put "${2#_}: ${line#\#define __NR_$1 }"
+				put "$3${line#\#define __NR_$1 }"
 				return 0
 				;;
 		esac
@@ -29,12 +29,12 @@ case "$2" in
 		;;
 	*)
 		status=0
-		get_def "$1" _32
+		get_def "$1" _32 "32: "
 		: $(( status += $? ))
 
-		get_def "$1" _64
+		get_def "$1" _64 "64: "
 		: $(( status += $? ))
 
-		exit "$status"
+		[ "$status" -eq 0 ] || die "not found"
 		;;
 esac
